In [1]:
import numpy as np

In [3]:
list(range(0,10)) #Array de Python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0,10,2) #Array de numpy, primero dato inicial, segundo dato de stop, tercero conteo 

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((10,5)) #Crear array en ceros, definir estructuras previas y se pueden hacer matrices

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((10,5)) #Crear array en unos, definir estructuras previas y se pueden hacer matrices

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.linspace(0,10,10) #Primer valor: es para iniciar, Segundo valor: Que termine, tercero: cuantos valores quiero

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
np.eye(4) #Crear matriz con diagonal espacial

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand() #Generar valor aleatorio entre cero y uno

0.8049362302476445

In [10]:
np.random.rand(4)

array([0.87744142, 0.3648542 , 0.22533291, 0.79331715])

In [ ]:
np.random.rand(4.4)

In [ ]:
np.random.randint(1,15)

In [ ]:
np.random.randint(1,100,(10,10)) #Generar matrices con numeros aleatorios.