In [ ]:
import numpy as np

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[0,2,45]])
print(matriz)
matriz.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0  2 45]]


2

In [ ]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2,vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


##Reto


In [25]:
tensor = np.array([[[[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]]]])
print(tensor)
tensor.ndim

[[[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]

   [[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]

   [[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]

   [[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]]]]


5

In [26]:
tensor_2 = np.expand_dims(tensor,axis=0)
print(tensor_2)
tensor_2.ndim

[[[[[[ 1  2  3]
     [ 4  5  6]
     [ 7  8  9]
     [ 0  2 45]]

    [[ 1  2  3]
     [ 4  5  6]
     [ 7  8  9]
     [ 0  2 45]]

    [[ 1  2  3]
     [ 4  5  6]
     [ 7  8  9]
     [ 0  2 45]]

    [[ 1  2  3]
     [ 4  5  6]
     [ 7  8  9]
     [ 0  2 45]]]]]]


6

In [27]:
print(tensor, tensor.ndim)
tensor_3 = np.squeeze(tensor)
print(tensor_3,tensor_3.ndim)

[[[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]

   [[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]

   [[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]

   [[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [ 0  2 45]]]]] 5
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]] 3
