In [1]:
import numpy as np
import pandas as pd

In [2]:
np.array(['hola','2','4','5'],dtype='float64')

ValueError: ignored

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_2 = np.linspace(0,10,100)

In [11]:
arr = np.array([13, 6, 3, 5, 10])

In [12]:
np.sort(arr) 

array([ 3,  5,  6, 10, 13])

In [13]:
arr = np.array([13, 6, 3, 5, 10])
np.max(arr)

13

In [14]:
arr = np.array([13, 6, 3, 5, 10])
np.argmax(arr)

0

In [15]:
arr = np.array([13, 6, 3, 5, 10]) 
arr[arr>7]

array([13, 10])