In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
arr

array([ 2, 15,  5, 10, 13,  1, 15, 15,  3,  2])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[ 2, 15,  5, 10, 13],
       [ 1, 15, 15,  3,  2]])

In [5]:
arr

array([ 2, 15,  5, 10, 13,  1, 15, 15,  3,  2])

In [6]:
arr.max()

15

In [8]:
matriz

array([[ 2, 15,  5, 10, 13],
       [ 1, 15, 15,  3,  2]])

In [9]:
matriz.max(0)

array([ 2, 15, 15, 10, 13])

In [10]:
arr.argmax() #Indice donde se encuentra el valor mas grande de nuestro array

1

In [11]:
matriz.argmax() #Indice donde se encuentra el valor mas grande de nuestro array

1

In [12]:
arr.min() #valor minimo de la funcion

1

In [13]:
matriz.min(0)

array([ 1, 15,  5,  3,  2])

In [14]:
arr.argmin()

5

In [15]:
matriz.argmin()

5

In [16]:
arr.ptp()

14

In [17]:
matriz.ptp(0) #Distacia del mayor al menor

array([ 1,  0, 10,  7, 11])

In [20]:
np.percentile(arr,50)

7.5

In [24]:
np.median(arr)

7.5

In [23]:
np.percentile(matriz,50,0)

array([ 1.5, 15. , 10. ,  6.5,  7.5])

In [27]:
np.median(matriz,0)

array([ 1.5, 15. , 10. ,  6.5,  7.5])

In [28]:
np.std(arr)

5.752390807307862

In [30]:
np.var(arr)

33.089999999999996

In [32]:
arr.sort()
arr

array([ 1,  2,  2,  3,  5, 10, 13, 15, 15, 15])

In [33]:
np.mean(arr)

8.1

In [34]:
np.mean(matriz,1)

array([ 2.6, 13.6])

In [40]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [41]:
a.ndim
b.ndim

1

In [42]:
b = np.expand_dims(b,axis=0)

In [43]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.concatenate((a,b.T),axis=1) #Con T mayuscula podemos hacer la transpuesta

array([[1, 2, 5],
       [3, 4, 6]])