In [6]:
import numpy as np

In [8]:
arr = np.random.randint(1,10,(3,2))
arr

array([[7, 9],
       [7, 2],
       [3, 5]])

In [9]:
arr.shape # Shape, cuantas filas y cuantas columnas tenemos

(3, 2)

In [11]:
arr.reshape(1,6) #Cambiar la forma de la matriz

array([[7, 9, 7, 2, 3, 5]])

In [12]:
arr.reshape(2,3)

array([[7, 9, 7],
       [2, 3, 5]])

In [13]:
np.reshape(arr,(1,6)) #Otra manera de hacer el reshape

array([[7, 9, 7, 2, 3, 5]])

In [14]:
arr #Arreglo original

array([[7, 9],
       [7, 2],
       [3, 5]])

In [15]:
np.reshape(arr,(2,3),'C') #Array en lenguaje C

array([[7, 9, 7],
       [2, 3, 5]])

In [16]:
np.reshape(arr,(2,3),'F') #Array en lenguaje Fortant

array([[7, 3, 2],
       [7, 9, 5]])

In [17]:
np.reshape(arr,(2,3),'A') #Guardado en el sistema

array([[7, 9, 7],
       [2, 3, 5]])

No se puede cambiar por dejar de respetar la forma original, esto quiere decir que la cantidad de valores

In [19]:
arr = np.random.randint(1,100,(5,9))
arr

array([[54, 45, 40, 43, 41, 83, 44, 98, 57],
       [ 7, 30, 98, 27, 84, 99, 10, 15, 24],
       [ 5, 80, 80, 62,  8, 16, 94, 29, 60],
       [57, 71, 96, 89, 18, 22, 12, 89, 12],
       [67, 61, 95, 96, 91, 18, 22, 25, 96]])

In [21]:
np.reshape(arr,(9,5),'C') #Array en lenguaje C

array([[54, 45, 40, 43, 41],
       [83, 44, 98, 57,  7],
       [30, 98, 27, 84, 99],
       [10, 15, 24,  5, 80],
       [80, 62,  8, 16, 94],
       [29, 60, 57, 71, 96],
       [89, 18, 22, 12, 89],
       [12, 67, 61, 95, 96],
       [91, 18, 22, 25, 96]])

In [22]:
np.reshape(arr,(2,3),'C') #Array en lenguaje C que no se puede compilar

ValueError: ignored