In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [3]:
arr

array([1, 2, 3, 4])

In [6]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [4]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [5]:
arr

array([1., 2., 3., 4.])

In [9]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [10]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [11]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S1')